method: 'HT'

data:
    root: './../data'
    dataset: 'cifar100'
    num_classes: 100

model:
    name: 'vit_base_patch16_224'

train:
    epoch: 50
    batch: 1000
    lr: 1e-3
    dropout: 0.
    optimizer: 'adam'
    criterion: 'CE'

    scheduler:
        warmup_lr_init: 1e-5
        warmup_t: 3
        k_decay: 1.
        lr_min: 1e-5
