method: 'HT'

data:
    root: './../data'
    dataset: 'food101'
    num_classes: 101

model:
    name: 'vit_base_patch16_224'

train:
    epoch: 50
    batch: 128
    lr: 1e-3
    dropout: 0.
    optimizer: 'adam'
    momentum: 0.9
    criterion: 'CE'

    scheduler:
        warmup_lr_init: 1e-2
        warmup_t: 5
        k_decay: 1.
        lr_min: 5e-4

