method: 'VP'

data:
    root: './../data'
    dataset: 'flowers102'
    num_classes: 102

model:
    name: 'vit_base_patch16_224'

prompt:
    size: 10

train:
    epoch: 50
    batch: 250
    lr: 1e-2
    dropout: 0.
    optimizer: 'adam'
    momentum: 0.9
    criterion: 'CE'

    scheduler:
        warmup_lr_init: 3e-2
        warmup_t: 5
        k_decay: 0.5
        lr_min: 1e-5

