method: 'VCAP'

data:
    root: './../data'
    dataset: 'cifar10'
    num_classes: 10

model:
    # name: 'vit_large_patch16_224.augreg_in21k'
    name: 'vit_base_patch16_224'
        
prompt:
    hidden_dim: 20
    bottle_neck: 10

train:
    epoch: 50
    batch: 128
    lr: 1e-3
    dropout: 0.
    optimizer: 'adam'
    momentum: 0.9
    criterion: 'CE'

    scheduler:
        warmup_lr_init: 1e-2
        warmup_t: 5
        k_decay: 1.
        lr_min: 1e-4

